#pragma once
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <termios.h>
#include <errno.h>
#include "gapbuffer.h"
#include "appendbuffer.h"
#include "GBLL.h"
#include "utils.h"
